name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8 isort autoflake

      - name: Auto-Fix Python Code
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports server/
          isort server/
          autopep8 --in-place --recursive server/

      - name: Run flake8 Linter
        run: |
          echo "Running flake8..."
          find ./server -name "*.py" -exec flake8 {} +
          echo "Linted all the Python files successfully ✅"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JS Linters
        run: |
          npm install --global jshint prettier

      - name: Auto-Fix JS Code with Prettier
        run: |
          prettier --write "server/database/**/*.js"

      - name: Run JSHint Linter
        run: |
          echo "Running JSHint..."
          find ./server/database -name "*.js" -exec jshint --config .jshintrc {} +
          echo "Linted all the JS files successfully ✅"
